version: '3'
services:
    quake2:
        image: inanimate/quake2:latest
        container_name: quake2_server
        volumes:
            - ${CONFIGS}/pak0.pak:/usr/share/games/quake2/baseq2/pak0.pak
            - ${CONFIGS}/quake2/server.cfg:/usr/share/games/quake2/baseq2/server.cfg
        env_file: uidgid.env
        ports:
            - "27910:27910/udp"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.filebrowser.rule= Host(`quake.${HOSTNAME}`)"
            - "traefik.http.services.filebrowser.loadbalancer.server.port=27910"
            - "traefik.http.routers.filebrowser.entrypoints=websecure"
            - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
        restart: always