version: '3'
services:
    # emby:
    #     image: emby/embyserver
    #     container_name: emby
    #     volumes:
    #         - /dev/rtc:/dev/rtc:ro
    #         - ${RUNTIME}/emby:/config
    #         - ${RAKAU}/TV:/data/tvshows:ro
    #         - ${RAKAU}/Movies:/data/movies:ro
    #         - ${RAKAU}/Anime:/data/anime:ro
    #         - ${RAKAU}/Music:/data/music:ro
    #     ports:
    #         - 1900:1900
    #         - 7359:7359
    #         - 8096:8096
    #         - 8920:8920
    #     env_file: uidgid.env
    #     environment:
    #         - VIRTUAL_HOST=emby.${HOSTNAME},cinema.${HOSTNAME},miru.${HOSTNAME},watch.${HOSTNAME}
    #         - VIRTUAL_PORT=8096
    #     hostname: Emby
    #     mem_limit: 16gb
    #     restart: always
    
    jellyfin:
        image: linuxserver/jellyfin
        container_name: jellyfin
        volumes:
            - /dev/rtc:/dev/rtc:ro
            - ${RUNTIME}/emby:/config
            - ${RAKAU}/TV:/data/tvshows:ro
            - ${RAKAU}/Movies:/data/movies:ro
            - ${RAKAU}/Anime:/data/anime:ro
            - ${RAKAU}/Music:/data/music:ro
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=jellyfin.${HOSTNAME},cinema.${HOSTNAME},miru.${HOSTNAME},watch.${HOSTNAME}
            - VIRTUAL_PORT=8096
        hostname: Jellyfin
        mem_limit: 16gb
        restart: always

    navidrome:
        image: deluan/navidrome:develop
        container_name: navidrome
        volumes:
            - ${RUNTIME}/navidrome-data:/data
            - ${RAKAU}/Music:/music:ro
        ports:
            - 4533:4533
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=navidrome.${HOSTNAME},listen.${HOSTNAME}
            - VIRTUAL_PORT=4533
            - ND_SCANINTERVAL=1m
            - ND_LOGLEVEL=info
            - ND_ENABLETRANSCODINGCONFIG=true
        mem_limit: 2gb
        restart: always