version: '2'
services:
    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        volumes:
            - ${DATA}/config/sabnzbd:/config
            - ${DATA}/Downloads/complete:/downloads
            - ${DATA}/Downloads/incomplete:/incomplete-downloads
        ports:
            - 8080:8080
        env_file: uidgid.env
        environment:
            - EDGE=1
            - VIRTUAL_HOST=sabnzbd.${HOSTNAME}
            - VIRTUAL_PORT=8080
        mem_limit: 2gb
        restart: always

    nzbget:
        image: ghcr.io/linuxserver/nzbget:latest
        container_name: nzbget
        volumes:
            - ${DATA}/config/nzbget:/config
            - ${DATA}/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - TZ=Europe/London
            - VIRTUAL_HOST=nzbget.${HOSTNAME},get.${HOSTNAME}
            - VIRTUAL_PORT=6789
        mem_limit: 2gb
        restart: always

    hydra2:
        image: hotio/nzbhydra2:latest
        container_name: hydra2
        volumes:
            - ${DATA}/config/hydra2:/config
        ports:
            - 5076:5076
        env_file: uidgid.env
        environment:
            - UMASK=002
            - VIRTUAL_HOST=hydra.${HOSTNAME},search.${HOSTNAME}
            - VIRTUAL_PORT=5076
            - TZ="Etc/UTC"
        mem_limit: 2gb
        restart: always
    
    radarr:
        image: ghcr.io/linuxserver/radarr:nightly
        container_name: radarr
        volumes:
            - ${DATA}/config/radarr:/config
            - ${DATA}/Downloads:/downloads
            - ${DATA}/Movies:/movies
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.${HOSTNAME},movies.${HOSTNAME}
            - VIRTUAL_PORT=7878
        mem_limit: 1gb
        restart: always    

    sonarr:
        image: ghcr.io/linuxserver/sonarr:preview
        container_name: sonarr
        volumes:
            - ${DATA}/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - ${DATA}/TV:/tv
            - ${DATA}/Anime:/anime
            - ${DATA}/Downloads:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.${HOSTNAME},tv.${HOSTNAME}
            - VIRTUAL_PORT=8989
        mem_limit: 1gb
        restart: always

    lidarr:
        image: ghcr.io/linuxserver/lidarr:nightly
        container_name: lidarr
        volumes:
            - ${DATA}/config/lidarr:/config
            - /etc/localtime:/etc/localtime:ro
            - ${DATA}/music:/music
            - ${DATA}/Downloads:/downloads
        ports:
            - 8686:8686
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=lidarr.${HOSTNAME},music.${HOSTNAME}
            - VIRTUAL_PORT=8686
        mem_limit: 1gb
        restart: always

    bazarr:
        image: ghcr.io/linuxserver/bazarr:latest
        container_name: bazarr
        volumes:
            - ${DATA}/config/bazarr:/config
            - /etc/localtime:/etc/localtime:ro
            - ${DATA}/TV:/tv
            - ${DATA}/Movies:/movies
        ports:
            - 6767:6767
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=bazarr.${HOSTNAME},subs.${HOSTNAME}
            - VIRTUAL_PORT=6767
        mem_limit: 256mb
        restart: always

    emby:
        image: emby/embyserver
        container_name: emby
        volumes:
            - ${DATA}/config/emby:/config
            - ${DATA}/TV:/data/tvshows:ro
            - ${DATA}/Movies:/data/movies:ro
            - ${DATA}/Anime:/data/anime:ro
            - /dev/rtc:/dev/rtc:ro
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=emby.${HOSTNAME},cinema.${HOSTNAME},miru.${HOSTNAME},watch.${HOSTNAME}
            - VIRTUAL_PORT=8096
        hostname: Emby
        mem_limit: 16gb
        restart: always