version: '3'
services:
    nquake:
        image: niclaslindstedt/nquakesv
        container_name: nquake_server
        environment:
          - HOSTNAME=${HOSTNAME}
          - SERVER_IP=quake.${HOSTNAME} # this is your server's external ip, leave it empty to look up your external ip
          - PORT=27500 # this is the external port number for this server
          - RCON_PASSWORD=GarbageDay
          - SERVER_ADMIN=GamerGoose
          - SERVER_MEMORY_KBYTES=65536 # memory allocation for server process
        volumes:
            - "/etc/timezone:/etc/timezone:ro" # This will make sure logs inside the container are in the timezone of the server
            - "/etc/localtime:/etc/localtime:ro" # This will make sure logs inside the container are in the timezone of the server
            - logs:/nquake/logs
            - media:/nquake/media
            - demos:/nquake/demos
            - ${RUNTIME}/qupak0.pak:/nquake/files/id1/pak0.pak
            - ${RUNTIME}/quake/pak1.pak:/nquake/files/id1/pak1.pak
        env_file: uidgid.env
        ports:
            - "27500:27500/udp"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nquake.rule= Host(`quake.${HOSTNAME}`)"
            - "traefik.http.services.nquake.loadbalancer.server.port=27500"
            - "traefik.http.routers.nquake.entrypoints=websecure"
            - "traefik.http.routers.nquake.tls.certresolver=myresolver"
        restart: always
    quake2:
        image: fortu/quake2-openffa
        container_name: quake2_server
        volumes:
            #- ${CONFIGS}/pak0.pak:/usr/share/games/quake2/baseq2/pak0.pak
            - ${CONFIGS}/quake2/server.cfg:/usr/share/games/quake2/baseq2/server.cfg
        env_file: uidgid.env
        ports:
            - "27910:27910/tcp"
            - "27910:27910/udp"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.quake2.rule= Host(`quake2.${HOSTNAME}`)"
            - "traefik.http.services.quake2.loadbalancer.server.port=27910"
            - "traefik.http.routers.quake2.entrypoints=websecure"
            - "traefik.http.routers.quake2.tls.certresolver=myresolver"
        restart: always

volumes:
  logs:
  demos:
  media: