version: '3'
services:
    # sabnzbd:
    #     image: linuxserver/sabnzbd:latest
    #     container_name: sabnzbd
    #     volumes:
    #         - ${RUNTIME}/sabnzbd:/config
    #         - ${DATA}/Downloads/complete:/downloads
    #         - ${DATA}/Downloads/incomplete:/incomplete-downloads
    #     ports:
    #         - 8080:8080
    #     env_file: uidgid.env
    #     environment:
    #         - EDGE=1
    #         - VIRTUAL_HOST=sabnzbd.${HOSTNAME}
    #         - VIRTUAL_PORT=8080
    #     mem_limit: 2gb
    #     restart: always

    nzbget:
        image: ghcr.io/linuxserver/nzbget:latest
        container_name: nzbget
        volumes:
            - ${CONFIG}/nzbget:/config
            - ${DATA}/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - TZ=Europe/London
            - VIRTUAL_HOST=nzbget.${HOSTNAME},get.${HOSTNAME}
            - VIRTUAL_PORT=6789
        mem_limit: 2gb
        restart: always

    hydra2:
        image: hotio/nzbhydra2:latest
        container_name: hydra2
        volumes:
            - ${RUNTIME}/hydra2:/config
        ports:
            - 5076:5076
        env_file: uidgid.env
        environment:
            - UMASK=002
            - VIRTUAL_HOST=hydra.${HOSTNAME},search.${HOSTNAME}
            - VIRTUAL_PORT=5076
            - TZ="Etc/UTC"
        mem_limit: 2gb
        restart: always
    
    radarr:
        image: ghcr.io/linuxserver/radarr:nightly
        container_name: radarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/radarr:/config
            - ${DATA}/Downloads/downloads
            - ${RAKAU}/Movies:/movies
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.${HOSTNAME},movies.${HOSTNAME}
            - VIRTUAL_PORT=7878
        mem_limit: 1gb
        restart: always    

    sonarr:
        image: ghcr.io/linuxserver/sonarr:preview
        container_name: sonarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/sonarr:/config
            - ${DATA}/Downloads/downloads
            - ${RAKAU}/TV:/tv
            - ${RAKAU}/Anime:/anime
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.${HOSTNAME},tv.${HOSTNAME}
            - VIRTUAL_PORT=8989
        mem_limit: 1gb
        restart: always

    lidarr:
        image: ghcr.io/linuxserver/lidarr:nightly
        container_name: lidarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/lidarr:/config
            - ${DATA}/Downloads/downloads
            - ${RAKAU}/Music:/music
        ports:
            - 8686:8686
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=lidarr.${HOSTNAME},music.${HOSTNAME}
            - VIRTUAL_PORT=8686
        mem_limit: 1gb
        restart: always

    bazarr:
        image: ghcr.io/linuxserver/bazarr:latest
        container_name: bazarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/bazarr:/config
            - ${RAKAU}/TV:/tv
            - ${RAKAU}/Movies:/movies
        ports:
            - 6767:6767
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=bazarr.${HOSTNAME},subs.${HOSTNAME}
            - VIRTUAL_PORT=6767
        mem_limit: 256mb
        restart: always

    unmanic:
        image: josh5/unmanic
        container_name: unmanic
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/unmanic:/config
            - ${RUNTIME}/unmanic-data/cache:/tmp/unmanic
            - ${RAKAU}/Movies:/library/Movies
        ports:
            - 8888:8888
        env_file: uidgid.env
        environment:
            - CONFIG_DIR=/config
            - LIBRARY_DIR=/library
            - TZ=Europe/London
            - VIRTUAL_HOST=unmanic.${HOSTNAME},transcode.${HOSTNAME}
            - VIRTUAL_PORT=8888
        mem_limit: 1gb
        cpus: 4
        restart: always
        