version: '3'
services:
    jmusicbot:
        image: twosevenska/jmusicbot:dev
        container_name: jmusicbot
        volumes:
            - ${CONFIGS}/jmusicbot/config.txt:/bot/config.txt
            - ${CONFIGS}/jmusicbot/serversettings.json:/bot/serversettings.json
            - ${RUNTIME}/jmusicbot-data/sounds:/sounds
        labels:
            - traefik.enable=false
        mem_limit: 1gb
        restart: always
    jsbmusicbot-backup:
        image: twosevenska/jsbmusicbot:dev
        container_name: jsbmusicbot-backup
        volumes:
            - ${CONFIGS}/jsbmusicbot/options.ini:/MusicBot/config/options.ini
            - ${CONFIGS}/jsbmusicbot/permissions.ini:/MusicBot/config/permissions.ini
        labels:
            - traefik.enable=false
        mem_limit: 1gb
        restart: always
