version: '2'
services:
    droppy:
        image: silverwind/droppy
        container_name: droppy
        volumes:
            - ${DATA}/config/droppy:/config
            - ${DATA}/fileServer/data:/files
        env_file: uidgid.env
        ports:
            - 8900:8989
        environment:
            - VIRTUAL_HOST=storage.${HOSTNAME}
            - VIRTUAL_PORT=8900
        mem_limit: 1gb
        restart: always
