version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - certs:/etc/nginx/certs:ro
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - conf:/etc/nginx/conf.d
            - dhparam:/etc/nginx/dhparam
            - ${CONFIGS}/nginx/custom.conf:/etc/nginx/conf.d/custom.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        environment:
            DEFAULT_HOST: domo-kun.duckdns.org
        mem_limit: 128m
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        restart: always

    nginx-proxy-le:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-letsencrypt
        volumes_from:
            - nginx-proxy
        volumes:
            - /etc/acme.sh
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment: 
            - VIRTUAL_PROTO=https
        depends_on:
            - nginx-proxy
        mem_limit: 128m
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - ${DATA}/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.${HOSTNAME}
            - LETSENCRYPT_HOST=muximux.${HOSTNAME}
        mem_limit: 64m
        restart: always

    homer:
        image: b4bz/homer:latest
        container_name: homer
        volumes:
            - ${DATA}/config/homer:/www/assets
            - ${CONFIGS}/homer/config.yml:/www/assets/config.yml
            - ${CONFIGS}/homer/logos:/www/assets/logos
            - ${CONFIGS}/homer/icons:/www/assets/icons
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=homer.${HOSTNAME},dashboard.${HOSTNAME}
        ports:
            - 8081:8080
        mem_limit: 64m
        restart: always

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --interval 7200
        mem_limit: 64m
        restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
