version: '3'
services:
    nzbget:
        image: ghcr.io/linuxserver/nzbget:latest
        container_name: nzbget
        volumes:
            - ${CONFIGS}/nzbget:/config
            - ${DATA}/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nzbget.rule= Host(`nzbget.${HOSTNAME}`) || Host(`get.${HOSTNAME}`)"
            - "traefik.http.routers.nzbget.entrypoints=websecure"
            - "traefik.http.routers.nzbget.tls.certresolver=myresolver"
        environment:
            - TZ=Europe/London
        mem_limit: 2gb
        restart: always

    hydra2:
        image: hotio/nzbhydra2:latest
        container_name: hydra2
        volumes:
            - ${RUNTIME}/hydra2:/config
        ports:
            - 5076:5076
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hydra2.rule= Host(`hydra.${HOSTNAME}`) || Host(`search.${HOSTNAME}`)"
            - "traefik.http.routers.hydra2.entrypoints=websecure"
            - "traefik.http.routers.hydra2.tls.certresolver=myresolver"
        environment:
            - UMASK=002
            - TZ="Etc/UTC"
        mem_limit: 2gb
        restart: always
    
    radarr:
        image: ghcr.io/linuxserver/radarr:nightly
        container_name: radarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/radarr:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/Movies:/movies
        ports:
            - 7878:7878
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radarr.rule= Host(`radarr.${HOSTNAME}`) || Host(`movies.${HOSTNAME}`)"
            - "traefik.http.routers.radarr.entrypoints=websecure"
            - "traefik.http.routers.radarr.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always    

    sonarr:
        image: ghcr.io/linuxserver/sonarr:preview
        container_name: sonarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/sonarr:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/TV:/tv
        ports:
            - 8989:8989
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule= Host(`sonarr.${HOSTNAME}`) || Host(`tv.${HOSTNAME}`)"
            - "traefik.http.routers.sonarr.entrypoints=websecure"
            - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    sonarr_anime:
        image: ghcr.io/linuxserver/sonarr:preview
        container_name: sonarr_anime
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/sonarrAnime:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/Anime:/anime
        ports:
            - 8990:8989
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr_anime.rule= Host(`sonarr-anime.${HOSTNAME}`) || Host(`anime.${HOSTNAME}`)"
            - "traefik.http.routers.sonarr_anime.entrypoints=websecure"
            - "traefik.http.routers.sonarr_anime.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    lidarr:
        image: ghcr.io/linuxserver/lidarr:nightly
        container_name: lidarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/lidarr:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/Music:/music
        ports:
            - 8686:8686
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lidarr.rule= Host(`lidarr.${HOSTNAME}`) || Host(`music.${HOSTNAME}`)"
            - "traefik.http.routers.lidarr.entrypoints=websecure"
            - "traefik.http.routers.lidarr.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    bazarr:
        image: ghcr.io/linuxserver/bazarr:latest
        container_name: bazarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/bazarr:/config
            - ${RAKAU}/TV:/tv
            - ${RAKAU}/Movies:/movies
        ports:
            - 6767:6767
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bazarr.rule= Host(`bazarr.${HOSTNAME}`) || Host(`subs.${HOSTNAME}`)"
            - "traefik.http.routers.bazarr.entrypoints=websecure"
            - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
        mem_limit: 256mb
        restart: always

    unmanic:
        image: josh5/unmanic
        container_name: unmanic
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIGS}/unmanic/settings.json:/config/.unmanic/config/settings.json
            - ${RUNTIME}/unmanic-data/cache:/tmp/unmanic
            - ${RAKAU}/Movies:/library/Movies
        ports:
            - 8888:8888
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.unmanic.rule= Host(`unmanic.${HOSTNAME}`) || Host(`transcode.${HOSTNAME}`)"
            - "traefik.http.routers.unmanic.entrypoints=websecure"
            - "traefik.http.routers.unmanic.tls.certresolver=myresolver"
        environment:
            - CONFIG_DIR=/config
            - LIBRARY_DIR=/library
            - TZ=Europe/London
        mem_limit: 1gb
        cpus: 4
        restart: always
        