version: '3'
services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        volumes:
            - ${RUNTIME}/filebrowser-data/database.db:/database.db
            - ${CONFIGS}/filebrowser/.filebrowser.json:/.filebrowser.json
            - ${RAKAU}:/rakau
        env_file: uidgid.env
        ports:
            - 8901:8901
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.filebrowser.rule= Host(`storage.${HOSTNAME}`)"
            - "traefik.http.services.filebrowser.loadbalancer.server.port=8901"
            - "traefik.http.routers.filebrowser.entrypoints=websecure"
            - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    youtube-dl:
        image: tzahi12345/youtubedl-material
        container_name: youtube-dl
        volumes:
            - ${RUNTIME}/youtube-dl-data:/app/appdata
            - ${RUNTIME}/youtube-dl-data/audio:/audio
            - ${RUNTIME}/youtube-dl-data/video:/video
            - ${RUNTIME}/youtube-dl-data/subscriptions:/subscriptions
            - ${CONFIGS}/youtube-dl/default.json:/app/appdata/default.json
        env_file: uidgid.env
        ports:
            - 17442:17442
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.youtube-dl.rule= Host(`youdown.${HOSTNAME}`)"
            - "traefik.http.routers.youtube-dl.entrypoints=websecure"
            - "traefik.http.routers.youtube-dl.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    webdav:
        image: ugeek/webdav:amd64
        container_name: webdav
        volumes:
            - ${RAKAU}:/media
        env_file: uidgid.env
        ports:
            - 8900:80
        env_file: 
            - uidgid.env
            - ${CONFIGS}/webdav/webdav.env
        environment:
            - TZ=Europe/London
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.webdav.rule= Host(`fs.${HOSTNAME}`)"
            - "traefik.http.routers.webdav.entrypoints=websecure"
            - "traefik.http.routers.webdav.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    resilio-sync:
        image: ghcr.io/linuxserver/resilio-sync
        container_name: resilio-sync
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/resilio-sync:/config
            - ${RUNTIME}/resilio-sync-data:/downloads
            - ${RAKAU}/Books:/sync
        env_file: uidgid.env
        ports:
            - 8902:8888
            - 55555:55555
        env_file: 
            - uidgid.env
        environment:
            - TZ=Europe/London
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.resilio-sync.rule= Host(`cloud.${HOSTNAME}`)"
            - "traefik.http.routers.resilio-sync.entrypoints=websecure"
            - "traefik.http.routers.resilio-sync.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always