version: '2'
services:
    emby:
        image: emby/embyserver
        container_name: emby
        volumes:
            - ${DATA}/config/emby:/config
            - ${DATA}/TV:/data/tvshows:ro
            - ${DATA}/Movies:/data/movies:ro
            - ${DATA}/Anime:/data/anime:ro
            - /dev/rtc:/dev/rtc:ro
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=emby.${HOSTNAME},cinema.${HOSTNAME},miru.${HOSTNAME},watch.${HOSTNAME}
            - VIRTUAL_PORT=8096
        hostname: Emby
        mem_limit: 16gb
        restart: always