version: '3'
services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        volumes:
            - ${RUNTIME}/filebrowser-data/database.db:/database.db
            - ${CONFIGS}/filebrowser/.filebrowser.json:/.filebrowser.json
            - ${RAKAU}:/rakau
        env_file: uidgid.env
        ports:
            - 8901:8901
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.filebrowser.rule= Host(`storage.${HOSTNAME}`)"
            - "traefik.http.services.filebrowser.loadbalancer.server.port=8901"
            - "traefik.http.routers.filebrowser.entrypoints=websecure"
            - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always

    youtube-dl:
        image: tzahi12345/youtubedl-material
        container_name: youtube-dl
        volumes:
            - ${RUNTIME}/youtube-dl-data:/app/appdata
            - ${RUNTIME}/youtube-dl-data/audio:/audio
            - ${RUNTIME}/youtube-dl-data/video:/video
            - ${RUNTIME}/youtube-dl-data/subscriptions:/subscriptions
            - ${CONFIGS}/youtube-dl/default.json:/app/appdata/default.json
        env_file: uidgid.env
        ports:
            - 17442:17442
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.youtube-dl.rule= Host(`youdown.${HOSTNAME}`)"
            - "traefik.http.routers.youtube-dl.entrypoints=websecure"
            - "traefik.http.routers.youtube-dl.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always