version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        mem_limit: 128m
        restart: always

    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        volumes:
            - ${DATA}/config/sabnzbd:/config
            - ${DATA}/Downloads/complete:/downloads
            - ${DATA}/Downloads/incomplete:/incomplete-downloads
        ports:
            - 8080:8080
        env_file: uidgid.env
        environment:
            - EDGE=1
            - VIRTUAL_HOST=sabnzbd.${HOSTNAME}
            - VIRTUAL_PORT=8080
        mem_limit: 2gb
        restart: always

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        volumes:
            - ${DATA}/config/couchpotato:/config
            - ${DATA}/Downloads/complete:/downloads
            - ${DATA}/Movies:/movies
        ports:
            - 5050:5050
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=couchpotato.${HOSTNAME}
            - VIRTUAL_PORT=5050
        mem_limit: 1gb
        restart: always
    
    plex:
        image: plexinc/pms-docker
        container_name: plex
        volumes:
            - ${DATA}/config/plex:/config
            - ${DATA}/appdata/plex/transcodes
            - ${DATA}/TV:/data/tvshows
            - ${DATA}/Movies:/data/movies
            - ${DATA}/Anime:/data/anime
        ports:
            - 32469:32469
            - 32400:32400/tcp
            - 32401:32401
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        env_file: uidgid.env
        environment:
            - TZ=Europe/London
            - VIRTUAL_HOST=plex.${HOSTNAME}
            - VIRTUAL_PORT=32400
            - ADVERTISE_IP=http://plex.${HOSTNAME}/
        hostname: PlexServer
        mem_limit: 16gb
        restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - ${DATA}/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - ${DATA}/TV:/tv
            - ${DATA}/Anime:/anime
            - ${DATA}/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.${HOSTNAME}
            - VIRTUAL_PORT=8989
        mem_limit: 1gb
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - ${DATA}/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.${HOSTNAME}
        mem_limit: 128m
        restart: always

#    nextcloud:
#        image: linuxserver/nextcloud
#        container_name: nextcloud
#        volumes:
#            - ${DATA}/config/nextcloud:/config
#            - ${DATA}/fileServer/data:/data
#            - /etc/localtime:/etc/localtime:ro
#        ports:
#            - 443:443
#        env_file: uidgid.env
#        environment:
#            - VIRTUAL_HOST=wurzcloud.${HOSTNAME}
#            - VIRTUAL_PORT=443
#        restart: always
#
#    mariadb:
#        image: linuxserver/mariadb
#        container_name: mariadb
#        volumes:
#            - ${DATA}/config/mariadb:/config
#            - /etc/localtime:/etc/localtime:ro
#        ports:
#            - 3306:3306
#        env_file: uidgid.env
#        restart: always
#
