version: '3'
services:
    emby:
        image: emby/embyserver
        container_name: emby
        volumes:
            - /dev/rtc:/dev/rtc:ro
            - ${RUNTIME}/emby:/config
            - ${RAKAU}/TV:/data/tvshows:ro
            - ${RAKAU}/Movies:/data/movies:ro
            - ${RAKAU}/Anime:/data/anime:ro
            - ${RAKAU}/Music:/data/music:ro
        ports:
            - 1900:1900
            - 7359:7359
            - 8096:8096
            - 8920:8920
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.emby.rule= Host(`emby.${HOSTNAME}`) || Host(`watch.${HOSTNAME}`) || Host(`miru.${HOSTNAME}`)"
            - "traefik.http.services.emby.loadbalancer.server.port=8096"
            - "traefik.http.routers.emby.entrypoints=websecure"
            - "traefik.http.routers.emby.tls.certresolver=myresolver"
        mem_limit: 16gb
        restart: always

    navidrome:
        image: deluan/navidrome:develop
        container_name: navidrome
        volumes:
            - ${RUNTIME}/navidrome-data:/data
            - ${RAKAU}/Music:/music:ro
        ports:
            - 4533:4533
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.navidrome.rule= Host(`navidrome.${HOSTNAME}`) || Host(`listen.${HOSTNAME}`)"
            - "traefik.http.routers.navidrome.entrypoints=websecure"
            - "traefik.http.routers.navidrome.tls.certresolver=myresolver"
        environment:
            - ND_SCANINTERVAL=1m
            - ND_LOGLEVEL=info
            - ND_ENABLETRANSCODINGCONFIG=true
        mem_limit: 2gb
        restart: always