version: '3'
services:
    # droppy:
    #     image: silverwind/droppy
    #     container_name: droppy
    #     volumes:
    #         - ${RUNTIME}/droppy:/config
    #         - ${RAKAU}/fileServer/data:/files
    #     env_file: uidgid.env
    #     ports:
    #         - 8900:8989
    #     environment:
    #         - VIRTUAL_HOST=storage.${HOSTNAME}
    #         - VIRTUAL_PORT=8900
    #     mem_limit: 1gb
    #     restart: always

    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        volumes:
            - ${RUNTIME}/filebrowser-data/database.db:/database.db
            - ${CONFIGS}/filebrowser/.filebrowser.json:/.filebrowser.json
            - ${RAKAU}:/rakau
        env_file: uidgid.env
        ports:
            - 8901:8901
        environment:
            - VIRTUAL_HOST=storage.${HOSTNAME}
            - VIRTUAL_PORT=8901
        mem_limit: 1gb
        restart: always

    youtube-dl:
        image: tzahi12345/youtubedl-material
        container_name: youtube-dl
        volumes:
            - ${RUNTIME}/youtube-dl-data:/app/appdata
            - ${RUNTIME}/youtube-dl-data/audio:/audio
            - ${RUNTIME}/youtube-dl-data/video:/video
            - ${RUNTIME}/youtube-dl-data/subscriptions:/subscriptions
            - ${CONFIGS}/youtube-dl/default.json:/app/appdata/default.json
        env_file: uidgid.env
        ports:
            - 17442:17442
        environment:
            - VIRTUAL_HOST=youdown.${HOSTNAME}
            - VIRTUAL_PORT=17442
        mem_limit: 1gb
        user: ${PUID}
        restart: always