version: '3'
services:
    lazylibrarian:
        image: ghcr.io/linuxserver/lazylibrarian
        container_name: lazylibrarian
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/lazylibrarian:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/Books:/books
        ports:
            - 5299:5299
        env_file: uidgid.env
        environment:
            - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lazylibrarian.rule= Host(`lazylibrarian.${HOSTNAME}`) || Host(`books.${HOSTNAME}`)"
            - "traefik.http.routers.lazylibrarian.entrypoints=websecure"
            - "traefik.http.routers.lazylibrarian.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always
