version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - ${CONFIGS}/nginx/custom.conf:/etc/nginx/conf.d/custom.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        mem_limit: 128m
        restart: always

    homer:
        image: b4bz/homer:latest
        container_name: homer
        volumes:
            - ${DATA}/config/homer:/www/assets
            - ${CONFIGS}/homer/config.yml:/www/assets/config.yml
            - ${CONFIGS}/homer/logos:/www/assets/logos
            - ${CONFIGS}/homer/icons:/www/assets/icons
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=homer.${HOSTNAME},dashboard.${HOSTNAME}
        ports:
            - 8081:8080
        mem_limit: 64m
        restart: always

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --interval 7200
        mem_limit: 64m
        restart: always
