version: '3'
services:
    readarr:
        image: hotio/readarr:nightly
        container_name: readarr
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${RUNTIME}/readarr:/config
            - ${DATA}/Downloads:/downloads
            - ${RAKAU}/Books:/books
        ports:
            - 8787:8787
        env_file: uidgid.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.readarr.rule= Host(`readarr.${HOSTNAME}`) || Host(`books.${HOSTNAME}`)"
            - "traefik.http.routers.readarr.entrypoints=websecure"
            - "traefik.http.routers.readarr.tls.certresolver=myresolver"
        mem_limit: 1gb
        restart: always
